version: '3.7'
services:
    go:
        init: true
        build: Dockerfiles/go
        volumes:
          - $HOME/Pictures/Photos2022:/photos
          - $HOME/.vim:/root/.vim
          - $HOME/.vimrc:/root/.vimrc
          - ./src:/app
        working_dir: /app
        environment:
          FROM_LOCATION: /photos/From
          TO_LOCATION: /photos/TO
        command: sleep infinity
    perl:
        init: true
        build: Dockerfiles/perl
        volumes:
          - /Users/mv/Pictures/Photos2022:/photos
          - .:/app
        working_dir: /app
        environment:
          FROM_LOCATION: /photos/From
          TO_LOCATION: /photos/TO
        command: sleep infinity
