version: '3.7'
services:
    app:
        init: true
        build: .
        volumes:
          - /Users/mv/Pictures/Photos2022:/photos
          - .:/app
        working_dir: /app
        environment:
          FROM_LOCATION: /photos/From
          TO_LOCATION: /photos/TO
        command: sleep infinity
