version: '3.7'
services:
    app:
        init: true
        build: .
        volumes:
          - ./:/app
        working_dir: /app
        environment:
          FROM_LOCATION: /app/test-from
          TO_LOCATION: /app/test-to
        command: sleep infinity
